# Generated by Django 3.2 on 2023-09-09 05:24

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='It must be a VALID 12 digits like 98xxxxxxxxxx', max_length=12, unique=True, validators=[utils.validators.PhoneNumberValidator()], verbose_name='phone number'),
        ),
    ]
