# Generated by Django 3.2 on 2023-09-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_employee_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='hourly_wage_base',
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='wage',
            field=models.PositiveIntegerField(default=2000000, verbose_name='wage'),
        ),
    ]
