# Generated by Django 3.2 on 2023-09-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20230910_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furlough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='from date')),
                ('till_date', models.DateField(verbose_name='till date')),
                ('is_approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Furlough',
                'verbose_name_plural': 'Furloughs',
                'db_table': 'furloughs',
            },
        ),
    ]
